services:
  adh-diary:
    restart: unless-stopped
    image: ghcr.io/rickenharp/adh_diary:main
    volumes:
      - "./database:/hanami/db"
    environment:
      HANAMI_ENV: production
      HANAMI_SERVE_ASSETS: "true"
      DATABASE_URL: "sqlite:///hanami/db/adh_diary.sqlite"
      SESSION_SECRET: fef55c1a5276b875cd33e5e89bedd0cae6771f22c2c4620faee58f7d5f61b65ee3ae018b390dc427868a442207921583068d5e64f1900cb4289df0d7a31b1234
    labels:
      - traefik.enable=true
      - traefik.http.routers.adh-diary.rule=Host(`adh-diary.rickenharp.cloud`)
      - traefik.http.routers.adh-diary.entrypoints=anubis # Listening on the exclusive Anubis Network
      - traefik.http.services.adh-diary.loadbalancer.server.port=2300
      - traefik.http.routers.adh-diary.service=adh-diary # Telling Traefik to use the above specified port
    networks:
      - proxy
networks:
  proxy:
    external: true