--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entries (
    id integer NOT NULL,
    date date NOT NULL,
    attention integer NOT NULL,
    organisation integer NOT NULL,
    mood_swings integer NOT NULL,
    stress_sensitivity integer NOT NULL,
    irritability integer NOT NULL,
    restlessness integer NOT NULL,
    impulsivity integer NOT NULL,
    side_effects text,
    blood_pressure text,
    weight double precision NOT NULL,
    user_id integer,
    medication_schedule_id integer NOT NULL
);


--
-- Name: entries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.identities (
    id integer NOT NULL,
    user_id integer,
    provider text,
    uid text,
    token text,
    refresh_token text,
    expires_at timestamp without time zone
);


--
-- Name: identities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.identities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.identities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medication_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medication_schedules (
    id integer NOT NULL,
    medication_id integer,
    user_id integer,
    morning double precision DEFAULT 0,
    noon double precision DEFAULT 0,
    evening double precision DEFAULT 0,
    before_bed double precision DEFAULT 0,
    notes text
);


--
-- Name: medication_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medication_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medication_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medications (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: medications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    password_salt text NOT NULL,
    locale text DEFAULT 'en'::text
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: weekly_reports; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.weekly_reports AS
 SELECT entries.user_id,
    to_char((entries.date)::timestamp with time zone, 'IYYY-"W"IW'::text) AS week,
    (array_agg(entries.date ORDER BY entries.date))[1] AS "from",
    (array_agg(entries.date ORDER BY entries.date DESC))[1] AS "to",
    (round(avg(entries.attention)))::integer AS attention,
    (round(avg(entries.organisation)))::integer AS organisation,
    (round(avg(entries.mood_swings)))::integer AS mood_swings,
    (round(avg(entries.stress_sensitivity)))::integer AS stress_sensitivity,
    (round(avg(entries.irritability)))::integer AS irritability,
    (round(avg(entries.restlessness)))::integer AS restlessness,
    (round(avg(entries.impulsivity)))::integer AS impulsivity,
    string_agg(NULLIF(entries.side_effects, ''::text), ','::text) AS side_effects,
    array_agg(entries.blood_pressure ORDER BY entries.date) AS blood_pressure,
    (array_agg(entries.weight ORDER BY entries.date))[1] AS weight,
    array_agg(DISTINCT concat(medications.name, ' ', medication_schedules.morning, 'mg')) AS medication
   FROM ((public.entries
     LEFT JOIN public.medication_schedules ON ((medication_schedules.id = entries.medication_schedule_id)))
     LEFT JOIN public.medications ON ((medications.id = medication_schedules.medication_id)))
  GROUP BY (to_char((entries.date)::timestamp with time zone, 'IYYY-"W"IW'::text)), entries.user_id
  ORDER BY (to_char((entries.date)::timestamp with time zone, 'IYYY-"W"IW'::text));


--
-- Name: entries entries_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_date_key UNIQUE (date);


--
-- Name: entries entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_pkey PRIMARY KEY (id);


--
-- Name: identities identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identities
    ADD CONSTRAINT identities_pkey PRIMARY KEY (id);


--
-- Name: medication_schedules medication_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medication_schedules
    ADD CONSTRAINT medication_schedules_pkey PRIMARY KEY (id);


--
-- Name: medications medications_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT medications_name_key UNIQUE (name);


--
-- Name: medications medications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT medications_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: entries_date_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX entries_date_index ON public.entries USING btree (date);


--
-- Name: identities_user_id_provider_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX identities_user_id_provider_index ON public.identities USING btree (user_id, provider);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: entries entries_medication_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_medication_schedule_id_fkey FOREIGN KEY (medication_schedule_id) REFERENCES public.medication_schedules(id);


--
-- Name: entries entries_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entries
    ADD CONSTRAINT entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: identities identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identities
    ADD CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: medication_schedules medication_schedules_medication_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medication_schedules
    ADD CONSTRAINT medication_schedules_medication_id_fkey FOREIGN KEY (medication_id) REFERENCES public.medications(id);


--
-- Name: medication_schedules medication_schedules_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medication_schedules
    ADD CONSTRAINT medication_schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20250609113142_create_entries.rb'),
('20250611091712_create_users.rb'),
('20250619131219_add_user_to_entries.rb'),
('20250619154513_add_dose_to_entry.rb'),
('20250619160833_add_medication_to_entry.rb'),
('20250620154450_make_email_unique.rb'),
('20250707111925_add_medications.rb'),
('20250707162552_make_user_medications_foreign_key.rb'),
('20250708121437_add_medication_schedule.rb'),
('20250709152754_switch_entries_to_medication_schedule.rb'),
('20250709203920_add_weekly_report_view.rb'),
('20250710102932_add_locale_to_user.rb'),
('20250715143059_add_identities.rb');
