#!/usr/bin/env -S usage bash

#MISE description="Reset the database to a well-known state"
#MISE alias="rdb"
#USAGE flag "-m --migrate" help="Migrate the database after recreation" default="false"

set -o errexit
set -o nounset
set -o pipefail

if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

main() {
  bundle exec hanami db drop
  bundle exec hanami db create
  psql "$DATABASE_URL" < /Users/alex/Downloads/adh_diary_2025-11-13T09:05:01+01:00.sql
  if [ "$usage_migrate" = "true" ]; then
    bundle exec hanami db migrate
  fi
}

main "$@"
