name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      HANAMI_ENV: test
      TZ: Europe/Berlin
      DATABASE_URL: postgres://postgres:postgres@localhost/adh_diary_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare env
        run: cp .env-example .env
      - name: Prepare database
        run: bundle exec hanami db prepare -e test
      - name: npm install
        run: npm install
      - name: Run all tests
        run: bundle exec rake ci