name: ci

on:
  push:
  pull_request:
    branches:
      - main
  create:

jobs:
  pre_job:
    permissions:
      actions: write
      contents: read
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  tests:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    env:
      HANAMI_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare env
        run: cp .env-example .env
      - name: Prepare database
        run: bundle exec hanami db prepare -e test
      - name: npm install
        run: npm install
      - name: Run all tests
        run: bundle exec rake ci