name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    env:
      HANAMI_ENV: test
      TZ: Europe/Berlin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare env
        run: cp .env-example .env
      - name: Prepare database
        run: bundle exec hanami db prepare -e test
      - name: npm install
        run: npm install
      - name: Run all tests
        run: bundle exec rake ci